; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -O0 -mtriple=riscv32 -mattr=+m -mattr=+xcorevsimd -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

declare i32 @llvm.riscv.cv.add.h(i32, i32)
declare i32 @llvm.riscv.cv.add.sc.h(i32, i32)
declare i32 @llvm.riscv.cv.add.sci.h(i32, i32)

define i32 @addh(i32 %a, i32 %b) {
; CHECK-LABEL: addh:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.add.h a0, a0, a1
; CHECK-NEXT:    ret
  %1 = call i32 @llvm.riscv.cv.add.h(i32 %a, i32 %b)
  ret i32 %1
}

define i32 @addsch(i32 %a, i32 %b) {
; CHECK-LABEL: addsch:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.add.sc.h a0, a0, a1
; CHECK-NEXT:    ret
  %1 = call i32 @llvm.riscv.cv.add.sc.h(i32 %a, i32 %b)
  ret i32 %1
}

define i32 @addscih(i32 %a, i32 %b) {
; CHECK-LABEL: addscih:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.add.sci.h a0, a0, 2
; CHECK-NEXT:    ret
  %1 = call i32 @llvm.riscv.cv.add.sci.h(i32 %a, i32 2)
  ret i32 %1
}
